version: 0.2
phases:
  install:
    runtime-versions:
        nodejs: 10
  build:
    commands:
      - npm install
      - export BUCKET=demosampledemo
      - aws cloudformation package --template-file template.yml --s3-bucket demosampledemo --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - template.yml
    - outputtemplate.yaml
